# Generated by Django 4.2.5 on 2023-11-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0009_alter_usuario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('numero_da_venda_realizada', models.AutoField(primary_key=True, serialize=False)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf_funcionario_realizou_a_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.funcionario')),
                ('endereco_entrega_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.usuario')),
                ('produtos_comprados', models.ManyToManyField(to='app_cad_usuarios.produto')),
            ],
        ),
    ]
