# Generated by Django 4.2.5 on 2023-11-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0011_alter_venda_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cpf_funcionario_realizou_a_venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.funcionario'),
        ),
    ]
