# Generated by Django 4.2.5 on 2023-11-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0012_alter_venda_cpf_funcionario_realizou_a_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
                ('estado', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='endereco_entrega_cliente',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_usuarios.endereco'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_usuarios.endereco'),
        ),
        migrations.AddField(
            model_name='venda',
            name='endereco_entrega_cliente',
            field=models.ManyToManyField(to='app_cad_usuarios.usuario'),
        ),
    ]
