# Generated by Django 4.2.5 on 2023-11-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0014_alter_funcionario_endereco_alter_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='endereco_entrega_cliente',
        ),
        migrations.AddField(
            model_name='venda',
            name='endereco_entrega_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.usuario'),
        ),
    ]
