# Generated by Django 4.2.5 on 2023-11-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0016_remove_venda_produtos_comprados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cpf_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cad_usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='endereco_entrega_cliente',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
