# -*- coding: utf-8 -*-
"""Cópia de Quinzena 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZl2lJqDE5ijnAP4jMYCrs7XJYwLDoOQ
"""

import matplotlib.pyplot as plt

import pandas as pd
df = pd.read_csv('/content/carnivorous_diet.csv',encoding='cp1252')
df

"""01) Título do Dataset;

R01: Dieta de carnívoros

02) Breve descrição;

R02: Dataframe mostrando a dieta de animais carnívoros, a família a que pertencem, os animais que devoram, o seu sexo, o ano da tabela, onde estão localizados, nomes científicos etc..

03) Tamanho;
"""

print(f'O dataframe possui {len(df)} linhas')

"""04) Extensão;

R04: A extensão do dataframe é .csv

05) Descrição das colunas existentes (nome, descrição, tipo, faixa de valores, etc);

R05: familyCarni = Essa coluna mostra a qual família pertence aquele animal.

scientificNameCarni = Mostra o nome científico do animal.

commonNameCarni = Nome popular do animal.

foodType = Tipo de alimentação

06) Quantidade de registros;
"""

print(f'O dataframe possui {len(df)} registros')

"""07) Extraia pelo menos 5 afirmações (insights) sobre os dados. Ex: Numa base de futebol: qual time marcou mais gols, qual time foi o mais vitorioso, qual time com a maior média de gols, etc."""

a = df['commonNameCarni'].value_counts().head(1)
b = df['foodType'].value_counts().head(1)
c = df['familyPrey'].value_counts().head(1)
d = df.groupby('sourceYear')['sourceYear'].count().sort_values(ascending = False).head(1)
e = df.groupby('sourceAuthor')['sourceAuthor'].count().sort_values(ascending = False).head(1)
print('O animal mais catalogado foi a raposa vermelha')
print('Os animais mais predados pertencem a classe dos mamíferos')
print('A familia animal mais predada foi a dos bovídeos')
print('O ano com mais registros foi 2010')
print('O autor com mais animais catalogados foi Sidorovich, V')

print(a)
print(b)
print(c)
print(d)
print(e)

"""08) Crie pelo menos 2 gráficos apresentando as informações de maior relevância no Dataset."""

a = df.groupby('familyCarni')['familyCarni'].count()
plt.figure(figsize=(25, 8))
plt.plot(a)
#Gráfico com as familias dos animais carnívoros catalogados e a quantidade de animais dessas familias

b = df.groupby('orderPrey')['orderPrey'].count()
plt.figure(figsize=(25, 8))
plt.plot(b)
#Gráfico com as ordens de animais mais predados e o número de animais predados em cada uma