# -*- coding: utf-8 -*-
"""Exercícios_Revisão_do_conteúdo_do_curso_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycd2OA3siPxp1-CdKyKJBLANpvQ5Ksnr

Lista de Exercícios - Revisão do conteúdo do curso Pandas do Kaggle 02.

01) Carregue o arquivo GSAF5.xls.csv em uma variável denominada df definindo a primeira coluna do arquivo como o índice das linhas.

Obs: O arquivo "GSAF5.xls.csv" pode ser encontrado em [Shark Attacks](https://www.kaggle.com/datasets/thedevastator/shark-attacks-the-risks-of-coastal-water-activit)
"""

pip install googletrans==3.1.0a0

import pandas as pd
from googletrans import Translator

df = pd.read_csv('/content/GSAF5.xls - GSAF5.xls (1).csv', index_col = 0)
df

"""02) Imprima as 8 primeiras linhas do DataFrame df."""

df.head(8)

"""03) Apresente a contagem de acidentes que acontenceram em cada pais. Ordene o resultado pela coluna pais de forma descendente."""

df.groupby('Country')['Case Number'].count().sort_values(ascending = False)

"""04) Qual a atividade que mais gera acidentes com tubarões?"""

df.groupby("Activity")['Activity'].count().sort_values(ascending = False)

"""05) É possível descobrir se existe alguma pessoa nesta base de dados que já tenha sofrido mais de um acidente com tubarões?"""

df['Name'].value_counts()

"""06) Quantos casos de Data Frame não possuem cadastro para a coluna 'Location'?"""

df.loc[df['Location'].isnull()]

"""07) Qual o tipo de dados da coluna Year?"""

df['Year'].dtype

"""08) Converta a coluna Year para int64. Sugestão: O parâmetro inplace pode ser utilizado para que a conversão seja gravada no Data Frame."""

df['Year'].fillna(0)
df['Year'] = pd.to_numeric(df['Year'] , errors='coerce')

"""09) Preencha todas as células vazias (NaN) da coluna Location com o termo 'Desconhecido'."""

df['Location'].fillna('Desconhecido', inplace = True)
df

"""10) Faça a tradução da coluna Type substituindo os termos em inflês por seus respectivos termos em português."""

tradutor = Translator()
lista = ['Unprovoked', 'Provoked', 'Invalid','Sea Disaster', 'Watercraft', 'Boat', 'Boating', 'Questionable', 'Unconfirmed', 'Unverified', 'Under investigation', 'Boatomg']
traducoes = tradutor.translate(lista, src='en', dest='pt')
a = 0
for traducao in traducoes[0:12]:
  print(traducoes[a].origin, '-->', traducoes[a].text)
  a += 1

df['Type'].replace({'Unprovoked': traducoes[0], 'Provoked' : traducoes[1], 'Invalid' : traducoes[2], 'Sea Disaster' : traducoes[3],
                    'Watercraft' : traducoes[4], 'Boat' : traducoes[5], 'Boating' : traducoes[6], 'Questionable' : traducoes[7],
                    'Unconfirmed' : traducoes[8], 'Unverified' : traducoes[9], 'Under investigation' : traducoes[10], 'Boatomg' : traducoes[11]}, inplace = True)
df

"""11) Renomeie a coluna 'Unnamed: 9' para 'Sexo'."""

df = df.rename(columns={'Unnamed: 9' : 'Sexo'})
df